
paths = [
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/12 String.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/6 String.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Ac Bass.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Aftertouch.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Ahh.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Al's Rhodes.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Analog Brass.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Arrangement.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Bellery.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Bowed String.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Cellos.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Clarinet.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Club Piano.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Crockett's.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Deep Purple.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Digi Piano.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Dragon Hall.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Electric Bass.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Flute.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/French Horn.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Fuzz Clav.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Glocken.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Gong of Kings.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Harpsichord.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Heavy Hitter.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Jan's Theme.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Jazz Harp.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Jazz Organ.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Kick Bass.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Kimono.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Marimba.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Music Box.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Nasty Brass.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Oboe.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Ole!.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Orchestra.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Pan Flute.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Piano 1.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Piano 2.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Pizzicato.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Pull Bass.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Reflection.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Return Home.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Saxy.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Sitar.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Steel Drums.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Steel Keys.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Stratocaster.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/String Ens.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/String Pad.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/StrutNstuff.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Terminator.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Trumpet.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Visitors.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Voice.wav",
  "Synthesizers/KawaiSynthesizers/Kawai K1R/Samples/Vybes.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/101_Bass.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/1137 1-Audio.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/1141 1-Audio.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/118 1-Audio.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/1192 1-Audio.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/12str_Gtr_1.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/12str_Gtr_2.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/12th_Knight.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/130 1-Audio.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/138 1-Audio.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/183 1-Audio.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/1_2_3_4_BPM.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/2.2_Bell_Pad.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/202_Rude_Bs.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/260&Juno.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/260_MIDI.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/2Trumpets.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/2_0_8_0.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/2_Square_Bass.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/2pole_Bass.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/303_Agressor.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/303_Bass.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/303_Hollow_BS.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/303_Ow_Bass.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/375 1-Audio.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/3D_Flanged.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/3_Osc_Brass.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/488 1-Audio.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/4_Hits_4_You.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/4_Pole_Bass.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/4pole_Bass.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/524 1-Audio.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/538 1-Audio.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/541 1-Audio.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/5th_Bell.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/5th_Dimension.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/5th_Lead.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/5th_Saw_Wave.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/5th_Sweep.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/5th_Wind.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/60's_LeadORG.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/624 1-Audio.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/64voicePiano.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/683 1-Audio.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/ARPsychea.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Ac.Upright.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Accordion_Fr.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Acid_Copter-1.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Acid_Copter.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Acid_Line.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Acid_Melt.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Acid_TB.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Acoustic_Bs..wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Adrenaline.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/AfricaVoices.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/AfricaZither.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/African_Snow.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Afro_Horns.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Afroharp_1.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Afroharp_Arq.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/After's_Pad.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/After_D!.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/After_Saw.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Afterlife.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Agogo.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Air_Lead.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Airplaaane.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Albion.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Alias_Square.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Alive.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Alpha_Zone.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Altamira.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Altern_Saw.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Alternative.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/AltoLead_Sax.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Alto_Sax-1.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Alto_Sax.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/AmbienceVibe.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Ambient_ORG.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Ambient_S_H.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Analog_Attax.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Analog_Clav1.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Analog_Clav2.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Analog_Drama.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Analog_Flute.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Analog_Lead.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Analog_Seq.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Angels_Sing.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Applause.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Arasian_Morn.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Archimede.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Arpege_Me.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Artificial.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Asian_Chord.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Asian_Dawn.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Assalt_Organ.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Atmos_Harp.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Atmosphere.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Atmospluck.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/AugerMentive.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Aurora.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Auto_TB-303.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Ayers_Rock.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/B'on_d'moov!.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Bag_Pipe.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Bagpipes.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Balafon _.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Balafon__.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Ballad_B.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Ballad_Trump.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/BandPass_Mod.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Banded_Jupe.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Bandolim.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Bandoneon.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Banjo.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Bari_Voise.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Baritone_Sax-1.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Baritone_Sax-2.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Baritone_Sax.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Barkit.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Bass_&_Lead.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Bass_In_Face.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Bass_Invader.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Bass_Marimba.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Bass_Pizz.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Bassic_Needs.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Bassoon.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Beauty_Bells.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Beauty_Vox.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Belfry_Chime.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/BellVox_1080.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Belltree_Vox.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Belly_Lead.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Berimbass.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Big_Blue.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Big_Bowls.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Bigband_Sax.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Biosphere.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Bird.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Biwa.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Black_Rain.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Black_Widow.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Blade_Racer.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Blip.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Blow_Hit.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Blown_Touch.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Blue_Notes.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/BluesHarp.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Blurpy.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Blusey_0D.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Bonang_Gam..wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Booster_Bips.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/BottleBell.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Bottle_Blow.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Bowed_Glass.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Brain_Waves.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Brass_1-1.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Brass_1.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Brass_Attack-1.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Brass_Attack.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Brass_It!.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Brass_Mutes.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Brass_Sect.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Breath_Drum.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Breath_Noise.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Breathy_Brs.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Bright_Piano.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Bright_Str.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Brightness.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/BritelowBass.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Brt._Dulcimer.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Bs_Pno+Brs.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Bushroot.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Buzz_Machine.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/C_Shell+echo.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Cabin_Organ.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Captain_Pizz.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Cascade.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Cathedral.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Cavaquinho.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Celesta.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Cello-1.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Cello.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Ceremony.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/CeremonyTimp.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/ChamberWinds.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/ChamberWoods.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Chambers.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Charang.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Chiffer_Lead.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Childlike.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Chime_Pad.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Chime_Wash.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/ChineseOrch1.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/ChineseOrch2.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Choir_Aahs.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Chord_Maj7th.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Chord_Min7th.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Chordmaj7_5-.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Chorus_Clav.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Church_Org.1.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Church_Pipes.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Cimbalom.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Civilization.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/ClariExpress.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Clarinet.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Clarinet_mp.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Classique.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Classy_Pulse.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Clav..wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Clavi-Club.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Clavicembalo.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Claviduck.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Clay_HouseBs.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Clean_Gt..wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Clear_Guitar.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Clk_AnalogBs.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Club_Organ.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Cold_JX.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Comp_Clav.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Comprex_Bass.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Compu_Bass.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/ComputerRoom.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Conch_Call.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Contrabass.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Crash_Pad.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Creamy.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Creator.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Crispy_Lead.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Crossbreed.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Crunch_Split.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Crystal.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Cuica.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Cuica_Steps.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Cutting_Edge.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Cyber_Bass.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Cyber_Dreams.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Cyber_Space.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Cyber_Swing.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Cyber_Trance.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/D'light.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/D-50_Heaven.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/D-50_Organ.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/D-50_Rhodes.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/D-50_Stacks.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/D-Mention.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/D50FantaPerc.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/DJ_Devil.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dance_Stack.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dark_Vox.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Darkshine.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dawn_2_Dusk.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/December_Sky.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Deep_Bass.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Deep_Machine.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Deep_Strings.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Delicate_EP.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dell_Ikhitt.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dense_Floor.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/DesertCrystl.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Didgeridoo.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Didgeridrone.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dig_Rhodes.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dimensional.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dingodrone-1.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dingodrone.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/DirtyLead_2.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dirty_Bass.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dirty_Organ-1.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dirty_Organ.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dirty_Organ_2.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dirty_Stack.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dissimilate-1.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dissimilate.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dist_Gtr_1.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dist_Gtr_2.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dist_TB-303.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Disto_Stack.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/DistortionGt.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Doos.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Drama_Pad.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dream_Organ.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dreamesque.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Drone_Split.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Drop_of_Rain.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Droplet.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Drum_n_Bass.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dual_Profs.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dulcimer.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dulcitar.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dunes.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dyna_Marimba.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Dyno_Toms.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/E-Motion_Pad.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/E.Com_Lead_1.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/E.Grand.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/E.Piano_1.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/E.Piano_2.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/EP+Mod_Pad.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Earblower.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Earth_Child.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Earth_Color.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Earth_Com_Bs.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/East_Europe.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/East_Melody.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/East_WestPlk.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/EasternTwang.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Eastvox.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Echo_Drops.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Echo_Piano.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Echo_Rhodes.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Echodrome.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Edgy_Organ.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Edye_Boost.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/English_Horn.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Enlighten.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Erhu_Lead.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Es_E.Piano.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Etherality.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Ethnic_VLNx3.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Ethno_Bass_1.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Ethno_Bass_2.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Ethno_Dreams.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Ethno_Metals.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Ethno_Pipes1.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Ethno_Pipes2.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Ethno_Pipes3.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Ethnopluck.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Euforia.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Euro-Dance_1.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Euro-Dance_2.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Euro_Bass.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Euro_Zither.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Exotic_Velo.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Exploration.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/FM_Bass.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/FM_BellPiano.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/FM_Tube_Bass.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/FXM_Saw_Lead.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Fancy_Pad.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Fantasia.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Fantasia_JV.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/FantasicPipe.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Fantasy_Vox.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Fantawine.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Far_East.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/FazzyCow_808.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Feed_Me!.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Feedback_VOX.wav",
  "Synthesizers/RolandSynthesizers/Roland JV-2080/Samples/Fiddle.wav"
]

import json
import urllib.parse

base_url = "https://raw.githubusercontent.com/pumodi/open-samples/main/"

def get_category(path):
    if "Kawai K1R" in path:
        return "Synthesizer - Kawai"
    if "Roland JV-2080" in path:
        return "Synthesizer - Roland"
    return "Other"

def clean_title(path):
    filename = path.split('/')[-1]
    return filename.replace('.wav', '').replace('_', ' ').replace('-', ' ').title()

items = []
current_id = 13 # Start after the existing 12

for p in paths:
    encoded_path = urllib.parse.quote(p)
    items.append({
        "id": str(current_id),
        "title": clean_title(p),
        "category": get_category(p),
        "duration": "0:05", # Default
        "url": base_url + encoded_path,
        "license": "MIT"
    })
    current_id += 1

print("export const soundItems: SoundItem[] = [")
# We'll need to manually merge with old ones or just replace if okay
# For now, let's just generate the new ones block
for item in items:
    print(f"    {json.dumps(item, indent=4)},")
print("];")
